version: '3'

services:
  # db:
  #   image: postgres:10.7
  #   environment: 
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=cuponzim
  #   volumes:
  #     - ./database/scripts:/docker-entrypoint-initdb.d
  #   ports:
  #     - "5433:5432"
  #   networks:
  #     - cuponzim

  node:
    image: node:12
    volumes:
      - .:/usr/src/cuponzim
    working_dir: /usr/src/cuponzim
    command: bash -c "npm install && npm run dev"
    ports:
      - "3333:3333"
    # depends_on:
    #   - db
    networks:
      - cuponzim

networks:
  cuponzim:
    driver: bridge